version: 1
formatters:
  main:
    format: '%(asctime)s %(levelname)s %(name)s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: main
    stream: ext://sys.stdout
root:
  level: INFO
  handlers: [console]

loggers:
  httpx:
    level: WARNING
    handlers: [console]
    propagate: no
  getsub:
    level: DEBUG
